name: Maven CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Set up Maven
      uses: s4u/setup-maven@v2
      with:
        maven-version: '3.8.6'

    - name: Build and test with Maven
      run: mvn -B verify

    - name: Code Quality Check
      run: mvn checkstyle:check

    - name: Security Scan
      run: mvn org.owasp:dependency-check-maven:check

    - name: Deployment
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: mvn deploy
